# Generated by Django 3.1 on 2021-06-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210625_1534'),
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
